[package]
name = "inquest"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = "1.0.0"
chrono = "0.4"
csv = "1.1"
bytes = "1.1.0"
linked-hash-map = "0.5.4"
reqwest = { version = "0.11.9", features = ["json"]}
scraper = "0.12.0"
select = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.17.0", features = ["full"] }
