[package]
name = "inquest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
bytes = "1.1.0"
linked-hash-map = "0.5.4"
scraper = "0.12.0"
select = "0.5.0"
serde_json = "1"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.sqlx]
version = "0.5.11"
features = ["chrono", "json", "runtime-tokio-rustls", "sqlite", "uuid"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]